// STA 104/114 (100 Level) — question bank
// Shared by Statistics, Industrial Mathematics, and Geology departments.
// Each question: { q: text, options: [A,B,C,D], correct: index of correct option (0-3) }

export const questions = [
    { q: "Statistical computing primarily refers to the application of _________ to solve statistical problems.", options: ["Mechanical engineering", "Computer science and programming techniques", "Civil engineering", "Environmental science"], correct: 1 },
    { q: "Which of the following is NOT an application area of computational statistics?", options: ["Machine Learning", "Data Mining", "Bioinformatics", "Architectural Design"], correct: 3 },
    { q: "A computer performs all the following functions EXCEPT", options: ["Accepting input", "Processing data", "Manufacturing hardware", "Producing output"], correct: 2 },
    { q: "Who developed the R programming language?", options: ["John Tukey and Ronald Fisher", "Ross Ihaka and Robert Gentleman", "Karl Pearson and Ronald Fisher", "Blaise Pascal and Charles Babbage"], correct: 1 },
    { q: "Which website is recommended for downloading R?", options: ["www.python.org", "www.cran.com", "www.r-project.org", "www.statistics.com"], correct: 2 },
    { q: "Which of the following is an advantage of R?", options: ["It is proprietary software.", "It requires expensive licenses.", "It is open-source.", "It supports only Windows."], correct: 2 },
    { q: "Which operator is used for exponentiation in R?", options: ["*", "**", "^", "%"], correct: 2 },
    { q: "According to the order of precedence, which operation is performed immediately after Brackets?", options: ["Addition", "Division", "Functions", "Multiplication"], correct: 2 },
    { q: "Which of the following is a homogeneous data structure in R?", options: ["Data frame", "List", "Vector", "Data frame and List"], correct: 2 },
    { q: "Which R function is primarily used to create a data frame?", options: ["vector()", "array()", "matrix()", "data.frame()"], correct: 3 },
    { q: "Which R command correctly calculates the square root of 64?", options: ["root(64)", "sqrt(64)", "square(64)", "sqr(64)"], correct: 1 },
    { q: "The output of the following command round(sqrt(49),2) is", options: ["6.90", "7.00", "49.00", "6.70"], correct: 1 },
    { q: "Which command rounds a number to a specified number of significant figures?", options: ["round()", "signif()", "trunc()", "digits()"], correct: 1 },
    { q: "The command factorial(6) returns", options: ["120", "360", "720", "620"], correct: 2 },
    { q: "Which R command computes 5 Combination 2?", options: ["perm(5,2)", "choose(5,2)", "combination(5,2)", "factorial(5,2)"], correct: 1 },
    { q: "The R command gamma(5) returns", options: ["120", "24", "5", "20"], correct: 1 },
    { q: "Which function returns the absolute value of a number?", options: ["abs()", "absolute()", "positive()", "magnitude()"], correct: 0 },
    { q: "Which R function calculates exponential values?", options: ["exponent()", "power()", "exp()", "expo()"], correct: 2 },
    { q: "In R, the mathematical constant π is represented by", options: ["pie", "PI", "pi", "Pi()"], correct: 2 },
    { q: "Which function is better suited for displaying multiple objects in one formatted line?", options: ["print()", "display()", "show()", "cat()"], correct: 3 },

    { q: "Which R function is used to standardize a numeric variable so that it has mean 0 and standard deviation 1?", options: ["normalize()", "scale()", "standard()", "center()"], correct: 1 },
    { q: "Which command produces only centered values (subtracting the mean without dividing by the standard deviation)?", options: ["scale(x)", "scale(x, scale=TRUE)", "scale(x, center=TRUE, scale=FALSE)", "scale(x, center=FALSE)"], correct: 2 },
    { q: "The command prod(c(2,4,6)) returns", options: ["12", "24", "48", "96"], correct: 2 },
    { q: "What is the output of trunc(98.987)", options: ["99", "98", "98.99", "99.00"], correct: 1 },
    { q: "Which function is used to calculate the time difference between two dates?", options: ["timediff()", "difftime()", "date()", "days()"], correct: 1 },
    { q: "Before using primeFactors(), which package should first be installed?", options: ["DescTools", "summarytools", "numbers", "moments"], correct: 2 },
    { q: "Which command loads the numbers package after installation?", options: ["require(numbers)", "library(numbers)", "load(numbers)", "package(numbers)"], correct: 1 },
    { q: "Which of the following correctly assigns the value 25 to variable x?", options: ["25=x", "x==25", "x<-25", "Both C and x=25"], correct: 3 },
    { q: "R programming language is", options: ["case-insensitive", "partially case-sensitive", "case-sensitive", "insensitive to variable names"], correct: 2 },
    { q: "Which command lists all variables currently available in the workspace?", options: ["dir()", "list()", "ls()", "objects()"], correct: 2 },
    { q: "Which command removes variable score from memory?", options: ["delete(score)", "erase(score)", "rm(score)", "remove(score)"], correct: 2 },
    { q: "Suppose age=c(12,15,19,21,16). Which command returns the number of elements?", options: ["count(age)", "size(age)", "length(age)", "elements(age)"], correct: 2 },
    { q: "Which command calculates the arithmetic mean of vector age?", options: ["average(age)", "avg(age)", "mean(age)", "amean(age)"], correct: 2 },
    { q: "Which command calculates the sample variance?", options: ["variance(x)", "var(x)", "sd(x)", "sample.var(x)"], correct: 1 },
    { q: "The command sd(x) computes", options: ["Standard Error", "Sample Standard Deviation", "Population Variance", "Range"], correct: 1 },
    { q: "Which command computes the Interquartile Range?", options: ["quartile(x)", "iqr(x)", "IQR(x)", "interquartile(x)"], correct: 2 },
    { q: "Which command returns both the minimum and maximum values of a dataset?", options: ["limits(x)", "minmax(x)", "range(x)", "boundary(x)"], correct: 2 },
    { q: "The command cor(x,y) computes", options: ["Covariance", "Correlation coefficient", "Coefficient of variation", "Standard error"], correct: 1 },
    { q: "Which command computes covariance?", options: ["cor(x,y)", "cov(x,y)", "var(x,y)", "relationship(x,y)"], correct: 1 },
    { q: "Suppose a vector contains missing observations (NA). Which argument should be included in mean() to ignore the missing values?", options: ["ignore=TRUE", "remove.na=TRUE", "na.rm=TRUE", "missing=FALSE"], correct: 2 },

    { q: "Which R function is used to create a sequence of numbers?", options: ["series()", "sequence()", "seq()", "range()"], correct: 2 },
    { q: "Which command creates the sequence 1, 3, 5, 7, 9?", options: ["seq(1,10,2)", "seq(1,9,by=2)", "seq(from=1,to=9,by=2)", "All of the above"], correct: 3 },
    { q: "Which command creates the sequence from 1 to 10?", options: ["1:10", "seq(1,10)", "seq(from=1,to=10)", "All of the above"], correct: 3 },
    { q: "The command iris[,2] extracts the second column of the iris dataset. This means:", options: ["Select all rows and column 2", "Select row 2 only", "Select column 1 only", "Select rows 2 and columns 2"], correct: 0 },
    { q: "Which command extracts rows 1 to 12 and columns 2 to 3 from the iris dataset?", options: ["iris[1:12,2:3]", "iris[c(1:12),c(2:3)]", "iris[1:12,c(2,3)]", "All of the above"], correct: 3 },
    { q: "Which command displays the first six observations of a dataset named dat?", options: ["first(dat)", "head(dat)", "top(dat)", "show(dat)"], correct: 1 },
    { q: "Which command displays the last eight observations of dat?", options: ["tail(dat,8)", "last(dat,8)", "head(dat,8)", "end(dat)"], correct: 0 },
    { q: "Which command displays the structure of a dataset?", options: ["summary(dat)", "class(dat)", "str(dat)", "View(dat)"], correct: 2 },
    { q: "Which command lists the variable names contained in a data frame?", options: ["labels(dat)", "variables(dat)", "names(dat)", "fields(dat)"], correct: 2 },
    { q: "Which command computes the minimum value of vector x1?", options: ["minimum(x1)", "min(x1)", "lowest(x1)", "smallest(x1)"], correct: 1 },
    { q: "Which command computes the maximum value of vector x1?", options: ["maximum(x1)", "max(x1)", "largest(x1)", "high(x1)"], correct: 1 },
    { q: "The command quantile(x1,0.25) computes the", options: ["First Quartile", "Second Quartile", "Third Quartile", "Median"], correct: 0 },
    { q: "Which command computes the third quartile?", options: ["quantile(x1,0.50)", "quantile(x1,0.75)", "quantile(x1,0.25)", "IQR(x1)"], correct: 1 },
    { q: "Which command computes the ninth decile?", options: ["quantile(x1,0.9)", "quantile(x1,9)", "decile(x1,9)", "IQR(x1)"], correct: 0 },
    { q: "Which command computes the standard deviation of all four numeric variables in the iris dataset simultaneously?", options: ["apply(dat,sd)", "lapply(dat[,1:4],sd)", "sd(dat)", "summary(dat)"], correct: 1 },
    { q: "Which command computes the variance of variables 2 and 3 simultaneously?", options: ["lapply(dat[,2:3],var)", "var(dat)", "variance(dat)", "apply(dat,var)"], correct: 0 },
    { q: "The summary() command provides all of the following EXCEPT", options: ["Minimum", "Mean", "Third Quartile", "Correlation Coefficient"], correct: 3 },
    { q: "When NA values are present, which command correctly computes the summary statistics?", options: ["summary(x)", "summary(x,na.rm=TRUE)", "summary(remove.na=TRUE)", "summary(x,ignore.na=TRUE)"], correct: 1 },
    { q: "Which command creates a data frame from variables age and salary?", options: ["frame(age,salary)", "table(age,salary)", "data.frame(age,salary)", "matrix(age,salary)"], correct: 2 },
    { q: "Which of the following statements about the iris dataset is TRUE?", options: ["It contains 100 observations and 4 variables.", "It contains 150 observations and 5 variables.", "It contains 200 observations and 6 variables.", "It contains 50 observations and 5 variables."], correct: 1 },
];