// STA 220/214 (200 Level) — question bank
// This pool has 100 questions; the exam engine randomly samples 60 per student.

export const questions = [
    // Set A — STA 220: Introduction to Data Science with Python (20)
    { q: "Which Python library is primarily used for data manipulation and analysis?", options: ["matplotlib", "pandas", "scipy", "seaborn"], correct: 1 },
    { q: "Which statement is used to import the pandas library?", options: ["import numpy as np", "import pandas as pd", "from pandas import *", "library(pandas)"], correct: 1 },
    { q: "Which function is used to read a CSV file into Python?", options: ["pd.read_excel()", "pd.read_csv()", "pd.import_csv()", "pd.load_csv()"], correct: 1 },
    { q: "Which function displays the first five observations of a DataFrame by default?", options: ["tail()", "info()", "head()", "shape()"], correct: 2 },
    { q: "Which function displays the last five observations in a DataFrame?", options: ["tail()", "head()", "sample()", "describe()"], correct: 0 },
    { q: "The primary purpose of mydata.head(10) is to:", options: ["Delete the first 10 observations", "Display the first 10 rows", "Count the first 10 variables", "Rename the first 10 columns"], correct: 1 },
    { q: "Which function is used to import an Excel file into Python?", options: ["pd.read_csv()", "pd.read_excel()", "pd.open_excel()", "pd.import_excel()"], correct: 1 },
    { q: "When reading an Excel workbook with multiple sheets, which argument specifies the sheet to be imported?", options: ["page=", "sheet_name=", "worksheet=", "tab="], correct: 1 },
    { q: "Which of the following formats is NOT an Excel file extension?", options: [".xlsx", ".xls", ".xlsm", ".csv"], correct: 3 },
    { q: "Which parameter in read_csv() specifies the delimiter used in the file?", options: ["header", "sep", "encoding", "na_values"], correct: 1 },
    { q: "Which parameter tells pandas how missing values are represented in a dataset?", options: ["na_values", "sheet_name", "skiprows", "chunksize"], correct: 0 },
    { q: "Which function provides a concise summary of a DataFrame, including data types and missing values?", options: ["info()", "describe()", "head()", "shape()"], correct: 0 },
    { q: "Which function generates descriptive statistics for numerical variables?", options: ["summary()", "statistics()", "describe()", "info()"], correct: 2 },
    { q: "The command pd.to_numeric(errors='coerce') converts invalid values into:", options: ["Zero (0)", "Blank spaces", "NaN", "Infinity"], correct: 2 },
    { q: "Which method allows the same function to be applied to several columns simultaneously?", options: ["append()", "merge()", "apply()", "concat()"], correct: 2 },
    { q: "The Interquartile Range (IQR) method is primarily used to:", options: ["Normalize data", "Detect outliers", "Remove duplicates", "Merge datasets"], correct: 1 },
    { q: "The Interquartile Range (IQR) is computed as:", options: ["Q1 + Q3", "Q3 − Q1", "Q3 ÷ Q1", "Q1 − Q3"], correct: 1 },
    { q: "According to the lecture notes, one advantage of logarithmic transformation is that it:", options: ["Increases missing values", "Reduces skewness and the influence of extreme values", "Removes all outliers completely", "Deletes duplicate observations"], correct: 1 },
    { q: "Winsorization is mainly used to:", options: ["Delete variables", "Cap extreme values while retaining observations", "Convert categorical variables to numeric", "Merge multiple datasets"], correct: 1 },
    { q: "Which command exports a pandas DataFrame to an Excel file?", options: ["to_csv()", "write_excel()", "to_excel()", "export_excel()"], correct: 2 },

    // Set B — Algorithmic modelling with complete data preprocessing pipeline (20)
    { q: "Which Python library is primarily used for data manipulation and analysis in the notebook?", options: ["NumPy", "Matplotlib", "Pandas", "TensorFlow"], correct: 2 },
    { q: "Which function is used to load a CSV file into a Pandas DataFrame?", options: ["pd.load_csv()", "pd.read_csv()", "pd.import_csv()", "pd.open_csv()"], correct: 1 },
    { q: "What is the primary purpose of the command mydata.head(10)?", options: ["Displays the last 10 observations", "Displays the first 10 observations", "Counts the total observations", "Removes the first 10 observations"], correct: 1 },
    { q: "Which command displays the last 10 records of a dataset?", options: ["mydata.end(10)", "mydata.bottom(10)", "mydata.tail(10)", "mydata.last(10)"], correct: 2 },
    { q: "The command mydata.info() is mainly used to", options: ["plot graphs.", "summarize the dataset structure.", "delete missing values.", "perform regression analysis."], correct: 1 },
    { q: "Which method provides descriptive statistics for numerical variables?", options: ["describe()", "summary()", "statistics()", "inspect()"], correct: 0 },
    { q: "Which of the following is NOT usually displayed by mydata.info()?", options: ["Number of observations", "Data types", "Memory usage", "Correlation coefficients"], correct: 3 },
    { q: "The command mydata.shape returns", options: ["only the number of columns.", "only the number of rows.", "the number of rows and columns.", "column names only."], correct: 2 },
    { q: "Which attribute returns the names of all variables in a DataFrame?", options: ["mydata.labels", "mydata.columns", "mydata.names", "mydata.variables"], correct: 1 },
    { q: "Why is data inspection performed immediately after importing a dataset?", options: ["To reduce computation time", "To verify successful import and understand the dataset", "To fit a regression model", "To standardize variables automatically"], correct: 1 },
    { q: "The command mydata['cut'].astype('category') converts the variable into", options: ["integer", "float", "categorical", "Boolean"], correct: 2 },
    { q: "Converting categorical variables into the category data type mainly helps to", options: ["increase file size.", "improve memory efficiency.", "increase missing values.", "remove duplicate observations."], correct: 1 },
    { q: "Which of the following variables is most appropriate for the category data type?", options: ["Price", "Weight", "Color", "Surface Area"], correct: 2 },
    { q: "Which function is commonly used to convert a text variable into datetime format?", options: ["pd.datetime()", "pd.to_datetime()", "pd.make_datetime()", "pd.date()"], correct: 1 },
    { q: "The command mydata.select_dtypes(include=np.number) selects", options: ["categorical variables only.", "numerical variables only.", "date variables only.", "Boolean variables only."], correct: 1 },
    { q: "Which statement best describes missing values?", options: ["Values greater than the mean", "Duplicate observations", "Unavailable or unknown observations", "Incorrect variable names"], correct: 2 },
    { q: "In Pandas, missing values are commonly represented as", options: ["None", "Empty string only", "NaN", "Zero"], correct: 2 },
    { q: "Why should missing values be handled before machine learning?", options: ["To increase the number of observations", "Because many algorithms cannot process missing values directly", "To increase memory usage", "To duplicate the dataset"], correct: 1 },
    { q: "Which of the following is an appropriate technique for handling missing numerical values?", options: ["Replace with the mean", "Replace with random letters", "Delete the variable immediately", "Convert to Boolean"], correct: 0 },
    { q: "A complete data preprocessing pipeline is primarily designed to", options: ["decorate graphs.", "prepare clean, consistent, and analysis-ready data.", "increase dataset size.", "eliminate all categorical variables."], correct: 1 },

    // Set C — Regression modelling pipeline (60)
    { q: "Which Python library is primarily used for manipulating tabular datasets?", options: ["NumPy", "pandas", "matplotlib", "TensorFlow"], correct: 1 },
    { q: "Which statement correctly imports the pandas library?", options: ["import pandas as np", "import numpy as pd", "import pandas as pd", "from pandas import numpy"], correct: 2 },
    { q: "Which function is used to load a CSV dataset into a pandas DataFrame?", options: ["pd.load_csv()", "pd.import_csv()", "pd.read_csv()", "pd.open_csv()"], correct: 2 },
    { q: "Consider the code df.head(). What does it display?", options: ["The last five observations", "Summary statistics", "First five observations", "Column names only"], correct: 2 },
    { q: "Which command displays the dimensions of a DataFrame?", options: ["df.length", "df.shape", "df.size()", "df.dimension"], correct: 1 },
    { q: "Which command displays concise information about all variables including their data types?", options: ["df.summary()", "df.describe()", "df.info()", "df.dtype()"], correct: 2 },
    { q: "Which function summarizes numerical variables?", options: ["df.summary()", "df.describe()", "df.statistics()", "df.mean()"], correct: 1 },
    { q: "Which command returns the total number of missing values in every column?", options: ["df.isnull().sum()", "df.null()", "df.empty()", "df.count()"], correct: 0 },
    { q: "Which method removes rows containing missing values?", options: ["df.remove()", "df.dropna()", "df.delete()", "df.clean()"], correct: 1 },
    { q: "Suppose df.fillna(df.mean(), inplace=True) is executed. What is its purpose?", options: ["Deletes missing values", "Replaces missing numerical values using column means", "Removes duplicate observations", "Converts data types"], correct: 1 },
    { q: "Which command identifies duplicate records?", options: ["df.duplicated()", "df.repeat()", "df.same()", "df.equals()"], correct: 0 },
    { q: "Which statement removes duplicated rows?", options: ["df.drop_duplicates()", "df.remove_duplicates()", "df.clean_duplicates()", "df.delete_duplicates()"], correct: 0 },
    { q: "Which code displays all unique categories in the Gender column?", options: ["df.unique(\"Gender\")", "df[\"Gender\"].unique()", "df.unique()", "df.show_unique()"], correct: 1 },
    { q: "Which encoding technique converts categorical variables into multiple binary variables?", options: ["Label Encoding", "One-Hot Encoding", "Standard Scaling", "Min-Max Scaling"], correct: 1 },
    { q: "Which function performs One-Hot Encoding using pandas?", options: ["pd.factorize()", "pd.get_dummies()", "pd.encode()", "pd.convert()"], correct: 1 },
    { q: "Given X = df.drop(\"Price\", axis=1), what does this statement accomplish?", options: ["Removes every row containing Price", "Selects Price as predictor", "Creates predictor variables by removing the target variable", "Deletes the dataset"], correct: 2 },
    { q: "Which statement correctly defines the response variable?", options: ["y = df[\"Price\"]", "X = df[\"Price\"]", "response = X", "df.response()"], correct: 0 },
    { q: "Which function is commonly used to divide data into training and testing datasets?", options: ["split_data()", "train_test_split()", "divide_data()", "data_split()"], correct: 1 },
    { q: "In train_test_split(X, y, test_size=0.2, random_state=42), what proportion of the dataset is reserved for testing?", options: ["10%", "15%", "20%", "42%"], correct: 2 },
    { q: "Why is the parameter random_state=42 frequently specified?", options: ["To improve prediction accuracy", "To reduce missing values", "To ensure reproducible train-test splits", "To normalize variables"], correct: 2 },
    { q: "Which module is imported to perform feature scaling using StandardScaler?", options: ["from sklearn.preprocessing import LabelEncoder", "from sklearn.preprocessing import StandardScaler", "from sklearn.linear_model import StandardScaler", "from sklearn.metrics import StandardScaler"], correct: 1 },
    { q: "Consider scaler = StandardScaler(); X_scaled = scaler.fit_transform(X). What is the primary purpose of this code?", options: ["Remove duplicate observations", "Encode categorical variables", "Standardize predictor variables", "Predict the target variable"], correct: 2 },
    { q: "After applying StandardScaler, the transformed variables generally have:", options: ["Mean = 1 and Standard Deviation = 0", "Mean = 0 and Standard Deviation = 1", "Mean = 100 and Standard Deviation = 10", "Values between 0 and 1"], correct: 1 },
    { q: "Which scaler transforms values into the interval [0, 1]?", options: ["StandardScaler()", "RobustScaler()", "MinMaxScaler()", "Normalizer()"], correct: 2 },
    { q: "Which statement correctly imports the Linear Regression model?", options: ["from sklearn.regression import LinearRegression", "from sklearn.linear_model import LinearRegression", "from sklearn.models import LinearRegression", "from sklearn.algorithm import LinearRegression"], correct: 1 },
    { q: "Consider model = LinearRegression(). What does this statement accomplish?", options: ["Fits the regression model", "Predicts the response variable", "Creates a Linear Regression model object", "Evaluates the model"], correct: 2 },
    { q: "Which command trains a Linear Regression model?", options: ["model.predict(X_train)", "model.train(X_train)", "model.fit(X_train, y_train)", "model.evaluate()"], correct: 2 },
    { q: "After fitting the model, which statement generates predictions?", options: ["model.predict(X_test)", "model.score(X_test)", "model.fit(X_test)", "model.summary()"], correct: 0 },
    { q: "Consider y_pred = model.predict(X_test). What is stored in y_pred?", options: ["Regression coefficients", "Predicted response values", "Training dataset", "Feature names"], correct: 1 },
    { q: "Which metric measures the average absolute prediction error?", options: ["accuracy_score()", "mean_absolute_error()", "precision_score()", "f1_score()"], correct: 1 },
    { q: "Which function calculates the Mean Squared Error?", options: ["mean_squared_error()", "mean_error()", "square_error()", "mse_score()"], correct: 0 },
    { q: "Which code correctly computes RMSE?", options: ["rmse = np.mean(mse)", "rmse = np.sqrt(mse)", "rmse = mse**2", "rmse = mse/2"], correct: 1 },
    { q: "Which metric indicates the proportion of variation explained by the regression model?", options: ["MAE", "RMSE", "R² Score", "MSE"], correct: 2 },
    { q: "Which function computes the coefficient of determination?", options: ["accuracy_score()", "r2_score()", "roc_auc_score()", "precision_score()"], correct: 1 },
    { q: "Consider print(model.coef_). What is displayed?", options: ["Predicted values", "Regression coefficients", "Training observations", "Missing values"], correct: 1 },
    { q: "Which statement displays the intercept of the fitted regression model?", options: ["model.intercept_", "model.constant_", "model.bias_", "model.alpha_"], correct: 0 },
    { q: "Suppose the regression equation is Ŷ = 12.4 + 3.8X. What is the predicted value when X = 5?", options: ["19.0", "25.4", "31.4", "17.4"], correct: 2 },
    { q: "What is the main purpose of residual analysis?", options: ["To encode categorical variables", "To determine whether prediction errors satisfy regression assumptions", "To split the dataset", "To calculate missing values"], correct: 1 },
    { q: "Which plot is commonly used to compare actual and predicted values?", options: ["Pie Chart", "Histogram", "Scatter Plot", "Box Plot"], correct: 2 },
    { q: "Consider mae = mean_absolute_error(y_test, y_pred); print(mae). If the output is 2.13, what does this imply?", options: ["The model correctly predicts 2.13 observations.", "Predictions differ from actual values by an average of approximately 2.13 units.", "The model explains 2.13% of the variation.", "The regression coefficient equals 2.13."], correct: 1 },
    { q: "Consider a Pipeline combining a scaler and a LinearRegression model. What is the major advantage of using a Pipeline?", options: ["It increases the dataset size.", "It automatically removes duplicates.", "It combines preprocessing and model training into one workflow.", "It automatically selects the best regression model."], correct: 2 },
    { q: "Why should feature scaling be fitted only on the training dataset?", options: ["To reduce memory usage", "To avoid data leakage", "To increase prediction speed", "To reduce the number of predictors"], correct: 1 },
    { q: "Which statement correctly applies an already fitted scaler to the testing data?", options: ["X_test = scaler.fit_transform(X_test)", "X_test = scaler.transform(X_test)", "X_test = scaler.scale(X_test)", "X_test = scaler.normalize(X_test)"], correct: 1 },
    { q: "What is the problem with fitting the scaler separately on X_train and X_test using fit_transform() on both?", options: ["The code contains a syntax error.", "The scaler is incorrectly fitted twice, leading to data leakage.", "The test data cannot be transformed.", "StandardScaler cannot transform test data."], correct: 1 },
    { q: "Consider cross_val_score(model, X, y, cv=5). What does cv=5 represent?", options: ["Five predictor variables", "Five regression models", "Five-fold cross-validation", "Five response variables"], correct: 2 },
    { q: "Cross-validation is mainly used to", options: ["remove missing values.", "estimate how well a model generalizes to unseen data.", "increase the number of observations.", "convert categorical variables."], correct: 1 },
    { q: "Suppose Training R² = 0.99 and Testing R² = 0.51. Which conclusion is most appropriate?", options: ["Excellent generalization", "Underfitting", "Overfitting", "Perfect prediction"], correct: 2 },
    { q: "Suppose Training R² = 0.42 and Testing R² = 0.39. The model most likely suffers from", options: ["Overfitting", "Underfitting", "Data leakage", "Multicollinearity"], correct: 1 },
    { q: "Which command predicts the response for a new observation new_data = [[1200, 3, 2]]?", options: ["model.predict(new_data)", "model.fit(new_data)", "model.score(new_data)", "model.evaluate(new_data)"], correct: 0 },
    { q: "Consider prediction = model.predict([[1500, 4, 3]]); print(prediction). If the output is [275000], what does this mean?", options: ["The regression coefficient equals 275000.", "The predicted selling price is 275000.", "There are 275000 observations.", "The intercept equals 275000."], correct: 1 },
    { q: "Which preprocessing technique is most appropriate for converting the values Male/Female into 0/1?", options: ["Standard Scaling", "Label Encoding", "Min-Max Scaling", "PCA"], correct: 1 },
    { q: "Which command displays the names of all variables in a DataFrame?", options: ["df.columns", "df.names", "df.header", "df.variables"], correct: 0 },
    { q: "Consider X = df.drop(\"Salary\", axis=1); y = df[\"Salary\"]. Why is Salary removed from X?", options: ["It contains missing values.", "It is the response variable.", "It is categorical.", "It is duplicated."], correct: 1 },
    { q: "Which command displays the correlation matrix of numerical variables?", options: ["df.relationship()", "df.corr()", "df.correlation_matrix()", "df.association()"], correct: 1 },
    { q: "A predictor has a correlation coefficient of 0.96 with another predictor. What problem is likely present?", options: ["Class imbalance", "Multicollinearity", "Missing values", "Overfitting"], correct: 1 },
    { q: "Which visualization is commonly used to display the correlation matrix?", options: ["Pie Chart", "Heatmap", "Histogram", "Bar Chart"], correct: 1 },
    { q: "Which library is commonly used to produce sns.heatmap(df.corr(), annot=True)?", options: ["NumPy", "pandas", "seaborn", "scipy"], correct: 2 },
    { q: "Consider score = r2_score(y_test, y_pred); print(score). If the output is 0.93, what is the best interpretation?", options: ["The model makes errors in 93% of observations.", "The model explains approximately 93% of the variation in the response variable.", "The model has 93 predictor variables.", "The model accuracy is exactly 93%."], correct: 1 },
    { q: "Which of the following represents the correct sequence of a regression modelling pipeline?", options: ["Import Data → Train Model → Handle Missing Values → Predict", "Import Data → Data Cleaning → Feature Engineering → Train-Test Split → Feature Scaling → Train Model → Predict → Evaluate", "Feature Scaling → Import Data → Evaluate → Train Model", "Predict → Train Model → Import Data"], correct: 1 },
    { q: "A data scientist obtains MAE = 2.1, RMSE = 2.8, R² = 0.95. Which conclusion is most appropriate?", options: ["The model performs poorly because RMSE is greater than MAE.", "The model demonstrates strong predictive performance with relatively small prediction errors and high explanatory power.", "The model is underfitting because R² is close to 1.", "The model should be discarded because MAE is not zero."], correct: 1 },
];