// STA 304 (300 Level) — question bank (60 questions)

export const questions = [
    { q: "Python was officially first released in which year?", options: ["1989", "1990", "1991", "1994"], correct: 2 },
    { q: "Who developed the Python programming language?", options: ["James Gosling", "Dennis Ritchie", "Bjarne Stroustrup", "Guido van Rossum"], correct: 3 },
    { q: "Which of the following is NOT listed as an advantage of Python?", options: ["Extensive support libraries", "Automatic memory management", "Open-source community support", "Mandatory variable type declaration"], correct: 3 },
    { q: "Python is described as a dynamically typed language because:", options: ["Variables cannot change type once declared.", "Data types must always be specified before assignment.", "The data type is automatically determined from the assigned value.", "Only numerical variables are dynamically typed."], correct: 2 },
    { q: "Which Python keyword represents the absence of a value?", options: ["False", "Null", "Void", "None"], correct: 3 },
    { q: "How many reserved keywords are listed in the lecture note for Python?", options: ["30", "32", "34", "35"], correct: 3 },
    { q: "What is the output of the following Python expression? 22 % 4", options: ["4", "6", "2", "5"], correct: 2 },
    { q: "Which arithmetic operator is used for exponentiation in Python?", options: ["^", "*", "//", "**"], correct: 3 },
    { q: "Which Python library is imported to calculate the square root of a number?", options: ["statistics", "numpy", "pandas", "math"], correct: 3 },
    { q: "What is the output of round(5/9, 2)?", options: ["0.50", "0.55", "0.56", "0.60"], correct: 2 },
    { q: "In Python, a variable is best described as:", options: ["A reserved keyword used to define functions", "A memory location used to permanently store programs", "A named container used to store a value for processing", "A built-in function used for input and output"], correct: 2 },
    { q: "Consider one = 14; two = 10; print(one ** two). What is the purpose of the operator **?", options: ["Multiplication", "Integer Division", "Modulus", "Exponentiation"], correct: 3 },
    { q: "According to the lecture note, which statement about variable declaration in Python is correct?", options: ["Variables must be declared before they are assigned values.", "Python uses the var keyword to declare variables.", "A variable is created automatically when a value is assigned to it.", "Variables must always be assigned a data type before use."], correct: 2 },
    { q: "Which of the following is a valid Python variable name?", options: ["2Student", "Student Name", "Student-Name", "Student_Name"], correct: 3 },
    { q: "Which of the following variable names is NOT valid in Python?", options: ["Ade2307", "_Ade", "for", "Ade_2307"], correct: 2 },
    { q: "Consider James=81; JAMES=50; james=43; print(James). What will be displayed?", options: ["43", "50", "81", "Syntax Error"], correct: 2 },
    { q: "Consider x=200; y=400; m=700; print(2*x - 3*y + 10*m). What is the output?", options: ["5800", "6200", "7200", "8200"], correct: 1 },
    { q: "What is the output of x=\"12\"; y=\"14\"; print(x + y)?", options: ["26", "1214", "1412", "Error"], correct: 1 },
    { q: "Consider d=\"25\"; e=10; r=int(d); print(r + e). What will be displayed?", options: ["2510", "251", "35", "Error"], correct: 2 },
    { q: "Which Python function is used to convert an integer into a string?", options: ["int()", "float()", "str()", "type()"], correct: 2 },
    { q: "Which of the following is NOT one of the eight built-in Python data types discussed in the lecture note?", options: ["String", "Dictionary", "Queue", "Set"], correct: 2 },
    { q: "Which statement correctly describes a Python string?", options: ["A collection of only alphabetic characters", "A sequence of characters enclosed within single or double quotation marks", "A mutable numeric object", "A collection of Boolean values"], correct: 1 },
    { q: "Consider mary = \"She goes to school everyday within a week\"; print(mary[0:5]). What is the output?", options: ["She", "She g", "She go", "She goes"], correct: 1 },
    { q: "Which string method converts every alphabetic character to uppercase?", options: ["capitalize()", "upper()", "title()", "lower()"], correct: 1 },
    { q: "What is the output of x = \"Singing1234\"; print(x.isalpha())?", options: ["True", "False", "1234", "Error"], correct: 1 },
    { q: "Which string method returns the position of the first occurrence of a specified substring and returns -1 if it is not found?", options: ["index()", "replace()", "find()", "split()"], correct: 2 },
    { q: "Consider x = \"I need a baby girl\"; print(x.replace(\"girl\", \"boy\")). What will be displayed?", options: ["I need girl", "I need a baby girl", "I need a baby boy", "I need boy"], correct: 2 },
    { q: "Which Python data type is used to represent numbers containing decimal values?", options: ["int", "complex", "float", "bool"], correct: 2 },
    { q: "The Python expression x = 3 + 4j creates a variable of which data type?", options: ["Integer", "Float", "Complex", "Boolean"], correct: 2 },
    { q: "Which of the following Python expressions evaluates to False?", options: ["6 == 6", "5 > 3", "4 <= 5", "5 < 4"], correct: 3 },
    { q: "Which Python data type is described as an ordered collection of items enclosed in square brackets?", options: ["Tuple", "Set", "Dictionary", "List"], correct: 3 },
    { q: "Consider info = [12, 7.6, 89, 35, [2.6, 5.3], 22, 87]; print(info[4][1]). What is the output?", options: ["2.6", "5.3", "22", "89"], correct: 1 },
    { q: "Which list method is used to add a single element to the end of a list?", options: ["extend()", "append()", "insert()", "update()"], correct: 1 },
    { q: "Which list method removes and returns the last element of a list when no index is specified?", options: ["remove()", "delete()", "pop()", "clear()"], correct: 2 },
    { q: "Which statement correctly describes a Python tuple?", options: ["Mutable and unordered", "Immutable and ordered", "Mutable and indexed", "Unordered and dynamic"], correct: 1 },
    { q: "According to the lecture note, which two methods are available for tuple objects?", options: ["append() and remove()", "pop() and insert()", "count() and index()", "extend() and clear()"], correct: 2 },
    { q: "Which characteristic best describes a Python set?", options: ["Ordered and allows duplicates", "Immutable and indexed", "Unordered and does not allow duplicate values", "Ordered and mutable"], correct: 2 },
    { q: "Consider A = {12,11,13,45}; B = {15,67,12,11}; print(A.intersection(B)). What will be displayed?", options: ["{12, 11}", "{45, 67}", "{15, 67}", "{}"], correct: 0 },
    { q: "Which dictionary method returns all the keys contained in a dictionary?", options: ["values()", "items()", "keys()", "get()"], correct: 2 },
    { q: "Consider mydico = {\"name\":\"John\",\"age\":76,\"location\":\"Japan\"}; print(mydico[\"location\"]). What is the output?", options: ["John", "76", "Japan", "location"], correct: 2 },
    { q: "NumPy is an acronym for:", options: ["Numerical Programming", "Numerical Python", "Numeric Package for Python", "Number Processing"], correct: 1 },
    { q: "Which of the following statements about NumPy is TRUE?", options: ["NumPy is part of Python's Standard Library.", "NumPy can only perform matrix multiplication.", "NumPy provides efficient multidimensional arrays and scientific computing tools.", "NumPy can only be installed using pip."], correct: 2 },
    { q: "Which statement is used to import the NumPy library using the conventional alias?", options: ["import NumPy", "import numpy", "import numpy as np", "from numpy import array"], correct: 2 },
    { q: "Consider A=[12,36,7,8,3]; B=[3,9,7,4,6]; print(A + B). What will be the output?", options: ["[15, 45, 14, 12, 9]", "[9, 27, 0, 4, -3]", "[12, 36, 7, 8, 3, 3, 9, 7, 4, 6]", "A TypeError"], correct: 2 },
    { q: "Before converting lists into NumPy arrays, what happens when A - B is executed on two plain Python lists?", options: ["Python performs element-wise subtraction.", "Python concatenates the two lists.", "A TypeError is generated.", "The result is an empty list."], correct: 2 },
    { q: "Consider A = np.array([12,36,7,8,3]); B = np.array([3,9,7,4,6]); print(A + B). What is the output?", options: ["[12 36 7 8 3 3 9 7 4 6]", "[15 45 14 12 9]", "[9 27 0 4 -3]", "[4. 4. 1. 2. 0.5]"], correct: 1 },
    { q: "The object returned by x = np.array([45, 88, 90, 30]) belongs to which data type?", options: ["list", "tuple", "numpy.ndarray", "dictionary"], correct: 2 },
    { q: "Which NumPy function creates an array filled entirely with zeros?", options: ["np.empty()", "np.full()", "np.ones()", "np.zeros()"], correct: 3 },
    { q: "Consider k = np.full((2, 3), 9); print(k). What is the output?", options: ["[[2 3 9] [2 3 9]]", "[[9 9 9] [9 9 9]]", "[[3 3] [9 9]]", "[[18 18 18] [18 18 18]]"], correct: 1 },
    { q: "Which NumPy function generates evenly spaced values within a specified interval while excluding the stop value?", options: ["np.linspace()", "np.random.rand()", "np.arange()", "np.full()"], correct: 2 },
    { q: "Which Python library is specifically designed for data manipulation and analysis?", options: ["Matplotlib", "NumPy", "Pandas", "TensorFlow"], correct: 2 },
    { q: "Which of the following is NOT one of the two primary data structures provided by Pandas?", options: ["Series", "DataFrame", "Matrix", "None of the above"], correct: 2 },
    { q: "Which of the following statements correctly imports the Pandas library using its conventional alias?", options: ["import pandas", "import pandas as pd", "from pandas import dataframe", "import pd"], correct: 1 },
    { q: "Consider my_dic = {'Name':['Francis','Johnson','Terry'],'Age':[34,78,45]}; info = pd.DataFrame(my_dic). Which method of DataFrame creation is illustrated above?", options: ["Direct method", "Indirect method", "Array method", "CSV importation"], correct: 1 },
    { q: "Consider SS1 = pd.concat([SS1_A, SS1_B]). What is the primary purpose of the concat() function in this example?", options: ["To sort the DataFrame", "To merge two DataFrames vertically", "To remove duplicate rows", "To convert a Series into a DataFrame"], correct: 1 },
    { q: "Suppose the DataFrame SS1 contains a column named Gender. Which statement correctly selects only this column?", options: ["SS1.iloc['Gender']", "SS1['Gender']", "SS1(Gender)", "SS1.filter('Gender')"], correct: 1 },
    { q: "Consider SS1.iloc[4, 3] = 'Nursing'. What does this command accomplish?", options: ["Adds a new row to the DataFrame.", "Deletes the fourth row.", "Replaces the value at row index 4 and column index 3 with \"Nursing\".", "Creates a new column named Nursing."], correct: 2 },
    { q: "Which of the following statements filters all records where Age is less than 20?", options: ["SS1.filter(Age < 20)", "SS1[SS1.Age < 20]", "SS1.iloc[Age < 20]", "SS1.where(Age < 20)"], correct: 1 },
    { q: "Which Pandas function is commonly used to generate descriptive statistical summaries of numerical variables?", options: ["head()", "describe()", "shape()", "tail()"], correct: 1 },
    { q: "Which command is used to import an Excel workbook into a Pandas DataFrame?", options: ["pd.read_csv(\"REAL_GDP.xlsx\")", "pd.read_excel(\"REAL_GDP.xlsx\")", "pd.load_excel(\"REAL_GDP.xlsx\")", "pd.import_excel(\"REAL_GDP.xlsx\")"], correct: 1 },
];